name: Linting

on: [push]

jobs:
  lintcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8 isort

    - name: Run isort to check import order
      run: |
        isort . --check --diff --profile black

    - name: Run black to check code formatting
      run: |
        black . --check

    - name: Run flake8 to check code style
      run: |
        flake8 .
    